// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Loga um usuário com email e senha e retorna um token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Autentica um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de desenvolvimento",
                        "name": "X-Dev-UUID",
                        "in": "header"
                    },
                    {
                        "description": "Credenciais de Login",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token JWT",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Email ou senha inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "429": {
                        "description": "Muitas tentativas de login",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Cria uma nova conta de usuário com email e senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registra um novo usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de desenvolvimento",
                        "name": "X-Dev-UUID",
                        "in": "header"
                    },
                    {
                        "description": "Credenciais de Registro",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado com sucesso!",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Requisição inválida",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Usuário já existe",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cart/add": {
            "post": {
                "description": "Adiciona um chapéu ao carrinho do usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Adiciona um chapéu ao carrinho",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Item do carrinho",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Hat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cart/update": {
            "put": {
                "description": "Atualiza a quantidade de um item no carrinho",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Atualiza o carrinho",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Item do carrinho",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Hat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/checkout": {
            "post": {
                "description": "Finaliza o pedido do usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checkout"
                ],
                "summary": "Finaliza o pedido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Dados do pedido",
                        "name": "pedido",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/estoque": {
            "get": {
                "description": "Retorna o estoque atual de cada chapéu",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estoque"
                ],
                "summary": "Lista o estoque de chapéus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de desenvolvimento",
                        "name": "X-Dev-UUID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.Hat"
                            }
                        }
                    }
                }
            }
        },
        "/hats": {
            "get": {
                "description": "Retorna a lista de chapéus disponíveis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hats"
                ],
                "summary": "Lista todos os chapéus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de desenvolvimento",
                        "name": "X-Dev-UUID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Hat"
                            }
                        }
                    }
                }
            }
        },
        "/hats/{id}/estoque": {
            "patch": {
                "description": "Atualiza a quantidade de estoque de um chapéu pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hats"
                ],
                "summary": "Edita o estoque de um chapéu",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do chapéu",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nova quantidade de estoque (0 a 200)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.EstoquePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.Hat"
                        }
                    },
                    "400": {
                        "description": "Quantidade inválida ou erro de requisição",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Chapéu não encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pedido": {
            "post": {
                "description": "Registra os dados do pedido em memória",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pedido"
                ],
                "summary": "Registra um pedido",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de desenvolvimento",
                        "name": "X-Dev-UUID",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "JWT token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Dados do pedido",
                        "name": "pedido",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Pedido"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Pedido"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Acesso não autorizado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Produto sem estoque suficiente",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.EstoquePayload": {
            "type": "object",
            "properties": {
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "handlers.Hat": {
            "type": "object",
            "properties": {
                "categoria": {
                    "description": "nacional, importado, crescer",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "handlers.HatPedido": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "handlers.Pedido": {
            "type": "object",
            "properties": {
                "cpf": {
                    "type": "string"
                },
                "cupom": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.HatPedido"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "pagamento": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "models.Hat": {
            "type": "object",
            "properties": {
                "categoria": {
                    "description": "nacional, importado, crescer",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "quantidade": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "rememberMe": {
                    "type": "boolean"
                }
            }
        },
        "models.Pedido": {
            "type": "object",
            "properties": {
                "bairro": {
                    "type": "string"
                },
                "cep": {
                    "type": "string"
                },
                "cidade": {
                    "type": "string"
                },
                "cpf": {
                    "type": "string"
                },
                "cupom": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endereco": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "itens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Hat"
                    }
                },
                "nome": {
                    "type": "string"
                },
                "numero": {
                    "type": "string"
                },
                "pagamento": {
                    "description": "\"pix\" ou \"boleto\"",
                    "type": "string"
                },
                "telefone": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                },
                "uf": {
                    "type": "string"
                }
            }
        },
        "models.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "hatstore-prd.fly.dev",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Hat Store API",
	Description:      "API da loja de chapéus Hat Store.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
