openapi: 3.0.0
info:
  title: Had Store API
  description: API da loja de chapéus Had Store.
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /cart/add:
    post:
      summary: Adiciona um chapéu ao carrinho
      description: Adiciona um chapéu ao carrinho do usuário
      operationId: addHatToCart
      tags:
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hat'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /cart/update:
    put:
      summary: Atualiza o carrinho
      description: Atualiza a quantidade de um item no carrinho
      operationId: updateCart
      tags:
        - cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hat'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /checkout:
    post:
      summary: Finaliza o pedido
      description: Finaliza o pedido do usuário
      operationId: checkout
      tags:
        - checkout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /hats:
    get:
      summary: Lista todos os chapéus
      description: Retorna todos os chapéus disponíveis
      operationId: listHats
      tags:
        - hats
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hat'
  /pedido:
    post:
      summary: Registra um pedido
      description: Registra os dados do pedido em memória
      operationId: registerOrder
      tags:
        - pedido
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
components:
  schemas:
    Pedido:
      type: object
      required:
        - nome
        - cpf
        - email
        - telefone
        - endereco
        - numero
        - bairro
        - cep
        - cidade
        - uf
        - pagamento
        - itens
        - total
      properties:
        nome:
          type: string
          example: "João da Silva"
        cpf:
          type: string
          example: "123.456.789-00"
        email:
          type: string
          example: "joao@email.com"
        telefone:
          type: string
          example: "(11) 91234-5678"
        endereco:
          type: string
          example: "Rua das Flores"
        numero:
          type: string
          example: "123"
        bairro:
          type: string
          example: "Centro"
        cep:
          type: string
          example: "12345-678"
        cidade:
          type: string
          example: "São Paulo"
        uf:
          type: string
          example: "SP"
        pagamento:
          type: string
          enum: [pix, boleto]
          example: "pix"
        itens:
          type: array
          items:
            $ref: '#/components/schemas/Hat'
        total:
          type: number
          format: float
          example: 199.90
    Hat:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        preco:
          type: number
          format: float
