basePath: /api
definitions:
  models.Hat:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: API da loja de chapéus Had Store.
  title: Had Store API
  version: "1.0"
paths:
  /cart/add:
    post:
      consumes:
      - application/json
      description: Adiciona um chapéu ao carrinho do usuário
      parameters:
      - description: Item do carrinho
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.Hat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Adiciona um chapéu ao carrinho
      tags:
      - cart
  /cart/update:
    put:
      consumes:
      - application/json
      description: Atualiza a quantidade de um item no carrinho
      parameters:
      - description: Item do carrinho
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.Hat'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Atualiza o carrinho
      tags:
      - cart
  /checkout:
    post:
      consumes:
      - application/json
      description: Finaliza o pedido do usuário
      parameters:
      - description: Dados do pedido
        in: body
        name: pedido
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Finaliza o pedido
      tags:
      - checkout
  /hats:
    get:
      description: Retorna todos os chapéus disponíveis
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Hat'
            type: array
      summary: Lista todos os chapéus
      tags:
      - hats
  /pedido:
    post:
      consumes:
      - application/json
      description: Registra os dados do pedido em memória
      parameters:
      - description: Dados do pedido
        in: body
        name: pedido
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registra um pedido
      tags:
      - pedido
swagger: "2.0"
